### PR TITLE
directly use buftok to avoid indirection through the line codec

### PR DESCRIPTION
**Pull request by colinsurprenant**
as discussed in #17 

this does not solve the flushing issue raised. we can either create a new PR for it or include that fix here.

### CODE REVIEW

**Comment by guyboertje** [comment]
Suggest:  get this merged and then deal with flush

**Comment by guyboertje** [comment]
LGTM
(did not test locally - I trust Jenkins for this small change)

**Comment by colinsurprenant** [comment]
For the sake of completeness I quickly measured the performance impact using `logstash-performance-testing` and the "json codec in/out" test and a few runs is showing an approximately 10% increase in TPS. The impact is not *massive* but it is not negligible either.

**Comment by colinsurprenant** [comment]
merging and pushing

**Comment by colinsurprenant** [comment]
published 2.0.5

**Pull request merged**
