### PR TITLE
support customizable delimiter for tokenizing

### LINKED ISSUE #14: support custom delimiter
see more at https://github.com/logstash-plugins/logstash-codec-line/issues/5

### PR DESCRIPTION
**Pull request by jsvd**
fixes #14

### CODE REVIEW

**Comment by jsvd** [comment]
jenkins, test this.

**Comment by jsvd** [comment]
jenkins, test it

**Comment by jsvd** [comment]
jenkins, test this please.

**Comment by jsvd** [comment]
oi? jenkins? come on! test it? pretty please?

**Comment by suyograo** [comment]
LGTM

**Pull request closed without merging**
